MobilePhoneWeb/WebMVC/Controllers/CreateOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMobile.Models;
using System.Data;
using System.Web.UI.HtmlControls;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml.Serialization;
using System.Text;

namespace WebMobile.Controllers
{
    public class CreateOrderController : Controller
    {
        //
        // GET: /CreateOrder/

        public ActionResult Index()
        {
            return View(db.vieworder());
        }

        public ActionResult ShowOrder(int idhd)
        {
            //            var dtod = db.detailorder(idhd);
            return View(db.detailorder(idhd));
        }
        public ActionResult Create()
        {
            if (Session["UserName"] != null)//đã đăng nhập.
            {
                 string username = Session["UserName"].ToString();// lấy tên của khách hàng
                 string password = Session["PassWord"].ToString();
                 using(var sl = new ServiceReferenceCustomer.ServiceCustomerClient())
                    {
                        string rule = "Kh";
                        var cus = sl.CheckLogin(username, password, rule);
                        var order = new OrderModel();
                        order.Customer_Name = cus.Name;
                        order.Address = cus.Address;
                        order.Phone = cus.Phone;
                        return View(order);
                    }
            }
            else
            {
                return View();
            }
           
           
        }
        [HttpPost]
        public ActionResult Create(OrderModel od)
        {
            if (ModelState.IsValid)
            {
                var order = new Order();
                order.Customer_Name = od.Customer_Name;
                order.Date = DateTime.Now;
                order.Phone = od.Phone;
                order.Status = "Chưa liên hệ";
                order.Address = od.Address;
                order.TotalMoney = MySession.COUNT;
                int id = db.InsertOrder(order);
                if (id!= 0)
                {
                    foreach (var i in MySession.GioHang)
                    {
                        var orderdt = new OrderDetail();
                        orderdt.Product_Id = i.ID.Value;
                        orderdt.Quantity = i.NUMBER.Value;
                        orderdt.Price = i.NUMBER.Value * i.PRICE.Value;
                        orderdt.Order_Id = id;
                        db.InsertOrderDetail(orderdt);
                    }
                    ResetCard();
                    return RedirectToAction("CreateSuccess");
                }
            }
            return View(od);   
        }
        public void ResetCard()
        {
            MySession.GioHang = null;
            Session[WebMobile.Models.MySession.TongSL] = null;
            MySession.COUNT = 0;
        }
        public ActionResult CreateSuccess()
        {
            return View();
        }

        public ActionResult ChangeStatus(int id)
        {

            if (db.ChangeStatus(id))
            {
                db.UpdateSoLuongSanPham(id);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }

        }
        public ActionResult CancelOrder(int id)
        {
            var or = new ServiceReferenceCreateOrder.ServiceOrderClient();
            if (db.CancelOrder(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Timkiem(FormCollection fc)
        {
            return RedirectToAction("OrderMonth", new { month = fc["month"], year = fc["year"] });
        }

        public ActionResult ExportData(int id)
        {
             StringBuilder sb = new StringBuilder();
            //static file name, can be changes as per requirement
            string sFileName = "Hoadon.xls";
            //Bind data list from edmx
            var Data = db.detailorder(id);
            if (Data != null && Data.Any())
            {
                sb.Append("<table style='2px solid black; font-size:15px;'>");
                sb.Append("<tr ALIGN="+"CENTER"+">");
                sb.Append("<td></td>");
                sb.Append("<td></td>");
                sb.Append("<td></td>");
                sb.Append("<td style='width:90px;'><b>Mã Sản Phẩm</b></td>");
                sb.Append("<td style='width:150px;'><b>Tên Sản Phẩm</b></td>");
                sb.Append("<td style='width:80px;'><b>Đơn Gía</b></td>");
                sb.Append("<td style='width:80px;'><b>Số lượng</b></td>");
                sb.Append("<td style='width:100px;'><b>Thành tiền</b></td>");
                sb.Append("</tr>");

                foreach (var result in Data)
                {
                    sb.Append("<tr ALIGN=" + "CENTER" + ">");
                    sb.Append("<td></td>");
                    sb.Append("<td></td>");
                    sb.Append("<td></td>");
                    sb.Append("<td>" + result.MaSP + "</td>");
                    sb.Append("<td>" + result.TenSP + "</td>");
                    sb.Append("<td>" + result.Gia + "</td>");
                    sb.Append("<td>" + result.SoLuong + "</td>");
                    sb.Append("<td>" + result.ThanhTien + "</td>");
                    sb.Append("</tr>");
                }
            }
            HttpContext.Response.AddHeader("content-disposition", "attachment; filename=" + sFileName);
            this.Response.ContentType = "application/vnd.ms-excel";
            byte[] buffer = System.Text.Encoding.UTF8.GetBytes(sb.ToString());
            return File(buffer, "application/vnd.ms-excel");          
        }

    }
}

MobilePhoneWeb/WebMVC/Views/CreateOrder/Create.cshtml
@model WebMobile.Models.OrderModel
<script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}
<link href="~/Content/Qstyle.css" rel="stylesheet" />
<div class="right-order">
    <div id="carttitle">
        <h2>Phiếu đặt hàng</h2>
     </div>

    <div id="ctl00_MainContentHolder_pnlWholeCart">
        <div id="cartcontainer">
            <div>
                <table id="ctl00_MainContentHolder_ItemGridView" class="cartproductgrid" border="0" style="width:100%; border-collapse:collapse; color:black; margin: 0px auto;">
                    <thead class="head-cart">
                        <tr>
                            <th align="left" scope="col">Tên sản phẩm</th>
                            <th align="right" scope="col">Đơn giá</th>
                            <th style="width:100px;" align="right" scope="col">Số lượng</th>
                            <th style="padding-left:20px;" align="right" scope="col">Thành tiền</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in WebMobile.Models.MySession.GioHang)
                        {
                            <tr>
                                <td style="width:200px;" class="productdetailscolumn" valign="top">
                                    <div id="ctl00_MainContentHolder_ItemGridView_ctl02_cartitemdescription" class="cartitemdescription">
                                        @Html.DisplayFor(m => item.NAME)
                                    </div>
                                </td>
                                <td style="width:150px;" class="productpricecolumn" valign="top" align="right">
                                    <span class="cartproductprice">@String.Format("{0:0,0}", Convert.ToInt32(item.PRICE))</span>
                                </td>
                                <td style="width:150px;" class="productquantitycolumn" valign="top" align="right">
                                    @Html.DisplayFor(m => item.NUMBER)
                                </td>
                                <td style="padding-left:20px; width: 160px;" class="producttotalcolumn" valign="top" align="right">
                                    <span class="lineitemnodiscounts"></span>
                                    <span class="product-price">@String.Format("{0:0,0}", Convert.ToInt32(item.COUNT))</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!--Cat xuong duoi-->
    </div>
    <div class="cartfooter">
        <div id="carttotals">
            <table cellspacing="0" cellpadding="3" border="0">
                <tbody>
                    <tr>
                        <td></td>
                        <td width="20">           </td>
                        <td class="formlabel"> Tổng tiền:</td>
                        <td class="sumprice">
                            <span id="ctl00_MainContentHolder_lblSubTotal">@String.Format("{0:0,0 Vnđ}", Convert.ToInt32(@WebMobile.Models.MySession.COUNT))</span>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>
    <div class="left-order">
        @using (Html.BeginForm("Create", "CreateOrder"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <fieldset>
                <legend class="header">Thông tin khách hàng</legend>
                <div class="editor-label">
                </div>
                <div class="editor-label">
                    Họ tên khách hàng:
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Customer_Name)
                    @Html.ValidationMessageFor(model => model.Customer_Name)
                </div>
                <div class="editor-label">
                    Địa chỉ:
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Address)
                    @Html.ValidationMessageFor(model => model.Address)
                </div>
                <div class="editor-label">
                    Số điện thoại
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Phone)
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>
                <p>
                    <input type="submit" class="submit_btn" value="Gửi Đơn Hàng" /> |
                    @Html.ActionLink("Trở lại", "MyCart", "MyCart")
                </p>

            </fieldset>
        }
</div>
<script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobilePhoneWeb/WebMVC/Views/CreateOrder/CreateSuccess.cshtml
@{
    ViewBag.Title = "CreateSuccess";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}
<pre style="font-family:Arial; font-size:16px; font-weight:bold;">
    Chúng tôi đã nhận được đơn đặt hàng của quý vị .
    Nhân viên của chúng tôi sẽ liên hệ ngay lại quý vị để chuyển hàng .
    Trong trường hợp bạn đã gửi đơn hàng quá lâu mà chưa nhận được phản hồi.
    Xin liên hệ với đường dây nóng của chúng tôi : 09xxx
    Cảm ơn đã mua hàng của chúng tôi !
</pre>

MobilePhoneWeb/WebMVC/Views/CreateOrder/Index.cshtml
@model IEnumerable<WebMobile.ServiceReferenceCreateOrder.Order>
@if (Session["Name"] != null)
{
    ViewBag.Title = "Hóa Đơn";
    ViewBag.Table1 = "Danh Sách Hóa Đơn";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    <div class="table-responsive">
        <div class="block menu-list supportlive">
            <h4 class="pd5x10 ">Thống kê hóa đơn theo tháng</h4>
            <ul class="nav nav-list w190px ">
                <div class="show" style="padding-top:10px; padding-bottom: 6px;">
                    @using (Html.BeginForm("Timkiem", "CreateOrder", FormMethod.Post))
                    {

                        <select name="month" style="height:28px;width:200px;">
                            <option value="0">Tháng-</option>
                            @for (int i = 0; i <= 12;i++ )
                            {
                                <option value="@i">@i</option>
                            }                          
                        </select>
                        <select name="year" style="height:28px;width:200px;">
                            <option value="0">Năm</option>
                            @for (int i = 2010; i <= DateTime.Now.Year;i++ )
                            {
                                <option value="@i">@i</option>
                            }
                            
                            
                        </select>
                        <input type="button" value="Lọc sản phẩm">
                    }
                </div>
            </ul>
        </div>

        <div class="Item-buttom">
            <div class="float-left">
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Mã hóa đơn</th>
                    <th>Tên khách hàng</th>
                    <th>Tình Trạng</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Tổng tiền</th>
                    <th>Ngày</th>
                    <th>Trạng Thái</th>
                    <th>Xuất hóa đơn</th>
                    <th>Tùy chọn</th>

                </tr>
            </thead>
            <tbody>
                @{
    foreach (var pro in Model)
    {
        <tr class="even gradeC">
            <th>@pro.Id</th>
            <th>@pro.Customer_Name</th>
            <th>@pro.Status</th>
            <th>@pro.Address</th>
            <th>@pro.Phone</th>
            <th>@pro.TotalMoney</th>
            <th>@pro.Date.Value.ToShortDateString()</th>
            @if (pro.Status == "Đã giao" | pro.Status == "Hủy")
            {
                <th></th>
            }
            else
            {
                <th>
                    @Html.ActionLink("Đổi", "ChangeStatus/" + pro.Id, "CreateOrder") | @Html.ActionLink("Hủy", "CancelOrder/" + pro.Id, "CreateOrder", null, new { onclick = "return confirm('Bạn có chắc hủy hóa đơn này, sau khi hủy sẽ không thể thay đổi được nữa?')" })
                </th>
            }
            <th>
                @Html.ActionLink("ExportData", "ExportData/" + pro.Id, "CreateOrder")
            </th>

            <th> <a href="@Url.Action("ShowOrder", "CreateOrder", new { idhd = @pro.Id})"> chi tiết</a></th>


            @*<th>@Html.Action("ShowOrder", "CreateOrder", new { idhd = @pro.Id})</th>*@
            @*| @Html.ActionLink("Sửa", "EditPro/" + pro.Id, "Product") | @Html.ActionLink("Xoá", "Delete/" + pro.Id, "Product", null, new { onclick = "return confirm('Bạn có chắc xóa?')" })</th>*@
        </tr>
    }
                }
            </tbody>
        </table>
    </div>
}
else
{
    Layout = "~/Views/Shared/_LayoutAdmin2.cshtml";
    <div>Bạn chưa đăng nhập, click vào @Html.ActionLink("Đây", "Login", "Login") để đăng nhập</div>
}

MobilePhoneWeb/WebMVC/Views/CreateOrder/OrderDetail.cshtml
@{
    ViewBag.Title = "OrderDetail";
}
@using WebMobile.Models

MobilePhoneWeb/WebMVC/Views/CreateOrder/OrderMonth.cshtml
@model IEnumerable<WebMobile.ServiceReferenceCreateOrder.Order>
@if (Session["Name"] != null)
{
    ViewBag.Title = "Hóa Đơn";
    ViewBag.Table1 = "Danh Sách Hóa Đơn";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    <div class="table-responsive">

        <div class="Item-buttom">
            <div class="float-left">
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Mã hóa đơn</th>
                    <th>Tên khách hàng</th>
                    <th>Tình Trạng</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Tổng tiền</th>
                    <th>Ngày</th>
                    <th>Trạng Thái</th>
                    <th>Tùy chọn</th>

                </tr>
            </thead>
            <tbody>
                @{
    foreach (var pro in Model)
    {
        <tr class="even gradeC">
            <th>@pro.Id</th>
            <th>@pro.Customer_Name</th>
            <th>@pro.Status</th>
            <th>@pro.Address</th>
            <th>@pro.Phone</th>
            <th>@pro.TotalMoney</th>
            <th>@pro.Date.Value.ToShortDateString()</th>
            @if (pro.Status == "Đã giao" | pro.Status == "Hủy")
            {
                <th></th>
            }
            else
            {
                <th>
                    @Html.ActionLink("Đổi", "ChangeStatus/" + pro.Id, "CreateOrder") | @Html.ActionLink("Hủy", "CancelOrder/" + pro.Id, "CreateOrder", null, new { onclick = "return confirm('Bạn có chắc hủy hóa đơn này, sau khi hủy sẽ không thể thay đổi được nữa?')" })
                </th>
            }

            <th> <a href="@Url.Action("ShowOrder", "CreateOrder", new { idhd = @pro.Id})"> chi tiết</a></th>


            @*<th>@Html.Action("ShowOrder", "CreateOrder", new { idhd = @pro.Id})</th>*@
            @*| @Html.ActionLink("Sửa", "EditPro/" + pro.Id, "Product") | @Html.ActionLink("Xoá", "Delete/" + pro.Id, "Product", null, new { onclick = "return confirm('Bạn có chắc xóa?')" })</th>*@
        </tr>
    }
                }
            </tbody>
        </table>
    </div>
}
else
{
    Layout = "~/Views/Shared/_LayoutAdmin2.cshtml";
    <div>Bạn chưa đăng nhập, click vào @Html.ActionLink("Đây", "Login", "Login") để đăng nhập</div>
}

MobilePhoneWeb/WebMVC/Views/CreateOrder/ShowOrder.cshtml
@model IEnumerable<WebMobile.ServiceReferenceCreateOrder.detailorder>
@if (Session["Name"] != null)
{
    ViewBag.Title = "ShowOrder";
    ViewBag.Table1 = "Danh Sách Sản Phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    
@*<script class ="server" >

  void Button_Click(Object sender, EventArgs e)
  {

    // Set the properties of the HtmlTable with the
    // user selections.
    Table1.BgColor = BgColorSelect.Value;
    Table1.Border = Convert.ToInt32(BorderSelect.Value);
    Table1.BorderColor = BorderColorSelect.Value;
    Table1.Height = HeightSelect.Value;
    Table1.Width = WidthSelect.Value;

  }

</script>*@

    <div class="table-responsive">
        <div class="Item-buttom">
            <div class="float-left">
                @*<a>@Html.ActionLink("Thêm Mới", "AddPro", "Product")</a>*@
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Mã Sản phẩm</th>
                    <th>Tên Sản phẩm</th>
                    <th>Đơn giá</th>
                    <th>Số lượng</th>
                    <th>Thành tiền</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pro in Model)
                {
                    <tr class=" even gradeMin">
                        <th>@pro.MaSP</th>
                        <th>@pro.TenSP</th>
                        <th>@pro.Gia</th>
                        <th>@pro.SoLuong</th>
                        <th>@pro.ThanhTien</th>
                        @*<th>@Html.ActionLink("Chi tiết", "Details/" + pro.Id, "Product") | @Html.ActionLink("Sửa", "EditPro/" + pro.Id, "Product") | @Html.ActionLink("Xoá", "Delete/" + pro.Id, "Product", null, new { onclick = "return confirm('Bạn có chắc xóa?')" })</th>*@
                    </tr>
                    @*@Html.ActionLink("ExportData", "ExportData/" + pro.MaHD,  "CreateOrder")*@
                }
            </tbody>
        </table>
    </div>
}
else
{
    Layout = "~/Views/Shared/_LayoutAdmin2.cshtml";
    <div>Bạn chưa đăng nhập, click vào @Html.ActionLink("Đây", "Login", "Login") để đăng nhập</div>
}